# This workflow always runs so we can test the action in pr.yml
# This workflow targets environment foo just like pr.yml 
name: deploy-foo
on:
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    environment: foo
    runs-on: ubuntu-latest
    steps:
      # sleep for 15 seconds to force this workflow to run longer than pr.yml so the action queues
      - shell: pwsh
        run: Start-Sleep -s 15
      - name: fake-deploy
        run: |
          echo 'fake'
