# This workflow always runs so we can test the action in pr.yml
# This workflow targets environment foo just like pr.yml
name: pr-completed
on:
  workflow_run:
    workflows: 
    - pr
    types: 
    - completed
jobs:
  post-pr:
    runs-on: windows-latest
    steps:
      # sleep to force this workflow to run longer than pr.yml so the action queues
      - shell: pwsh
        run: Start-Sleep -s 45