name: pr-validation
on:
  workflow_dispatch: # allow manual triggering
  pull_request:
    branches: [main]
jobs:
  sleep:
    runs-on: windows-latest
    steps:
      # sleep for 5 seconds to force the second job that targets environmment foo to run shortly after deploy-foo.yml runs
      - shell: pwsh
        run: Start-Sleep -s 5
  build-and-test:
    needs: sleep
    environment: foo
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
      fail-fast: false
    # runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # - name: run-deploy-foo
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh workflow run deploy-foo --ref ${{ github.event.pull_request.head.ref }}
      # - name: test-action
      #   uses: ./
      #   with:
      #     environment: foo
      - run: echo 'foo'
